#include "link-aware-admission.h"
#include "plc-link-profile.h"
#include <algorithm>
namespace ns3 {
LinkAwareAdmissionController::LinkAwareAdmissionController(uint32_t tCtrlSlots,uint32_t oMapSlots,uint32_t bAuthSlots):m_tCtrlSlots(tCtrlSlots),m_oMapSlots(oMapSlots),m_bAuthSlots(bAuthSlots){}
void LinkAwareAdmissionController::SetOrderingMode(OrderingMode mode){m_ordering=mode;}
std::vector<EvCommunicationDemand> LinkAwareAdmissionController::Ordered(std::vector<EvCommunicationDemand> d) const{ if(m_ordering==OrderingMode::WORST_LINK_FIRST){ std::stable_sort(d.begin(),d.end(),[](const auto&a,const auto&b){return ProfileRank(a.profileClass)>ProfileRank(b.profileClass);}); } return d; }
uint32_t LinkAwareAdmissionController::ComputeFinish(const std::vector<EvCommunicationDemand>& dc,uint32_t authSlots,uint32_t bPkt,uint32_t bBlk) const{ auto ordered=Ordered(dc); uint32_t sumReq=0,sumRes=0,firstReady=0; for(size_t i=0;i<ordered.size();++i){ sumReq+=ordered[i].cReqEffSlots; sumRes+=ordered[i].cResEffSlots; if(i==0) firstReady=ordered[i].cReqEffSlots+ordered[i].cProcSlots; bBlk=std::max(bBlk,ordered[i].bBlkSlots); } uint32_t responseStart=std::max(sumReq+authSlots+bPkt, firstReady); return m_oMapSlots+responseStart+sumRes+bBlk; }
AdmissionDecision LinkAwareAdmissionController::EvaluateActive(const std::vector<EvCommunicationDemand>& dc,const std::vector<EvCommunicationDemand>& slac,const EvCommunicationDemand& candidate,AdmissionMode mode) const{ std::vector<EvCommunicationDemand> useDc=dc; uint32_t authSlots=0; bool haveCredits=false; for(const auto& s:slac){ if(s.creditSlots>0){haveCredits=true;} authSlots+=s.creditSlots; } authSlots += (candidate.creditSlots>0?candidate.creditSlots:m_bAuthSlots); if(!haveCredits && slac.size()>0 && authSlots==(candidate.creditSlots>0?candidate.creditSlots:m_bAuthSlots)){ authSlots=m_bAuthSlots*(slac.size()+1); } /* Sum of per-link credits Q_{k'} = sum q_i (+ candidate); uniform q*(K+1) fallback when credits are not annotated. */ uint32_t bPkt=candidate.bPktSlots,bBlk=candidate.bBlkSlots; if(mode==AdmissionMode::COUNT_BASED_NOMINAL){ auto p=PlcLinkProfileTable::Get(PlcProfileClass::NOMINAL); for(auto& d:useDc){ d.cReqEffSlots=p.cReqEffSlots; d.cResEffSlots=p.cResEffSlots; d.bBlkSlots=p.bBlkSlots; } bPkt=p.bPktSlots; bBlk=p.bBlkSlots; } else if(mode==AdmissionMode::COUNT_BASED_WORST_CASE){ auto p=PlcLinkProfileTable::Get(PlcProfileClass::SEVERE); for(auto& d:useDc){ d.cReqEffSlots=p.cReqEffSlots; d.cResEffSlots=p.cResEffSlots; d.bBlkSlots=p.bBlkSlots; } bPkt=p.bPktSlots; bBlk=p.bBlkSlots; }
 uint32_t f=ComputeFinish(useDc,authSlots,bPkt,bBlk); AdmissionDecision out; out.finishSlots=f; out.slackSlots=static_cast<int64_t>(m_tCtrlSlots)-static_cast<int64_t>(f); out.admit=f<=m_tCtrlSlots; out.reason=out.admit?"admit":"CondA_fail"; return out; }
AdmissionDecision LinkAwareAdmissionController::EvaluateTerminal(const std::vector<EvCommunicationDemand>& projectedDc,AdmissionMode mode) const{ std::vector<EvCommunicationDemand> dc=projectedDc; uint32_t bBlk=0; if(mode==AdmissionMode::COUNT_BASED_NOMINAL){ auto p=PlcLinkProfileTable::Get(PlcProfileClass::NOMINAL); for(auto& d:dc){d.cReqEffSlots=p.cReqEffSlots;d.cResEffSlots=p.cResEffSlots;d.bBlkSlots=p.bBlkSlots;} bBlk=p.bBlkSlots; } else if(mode==AdmissionMode::COUNT_BASED_WORST_CASE){ auto p=PlcLinkProfileTable::Get(PlcProfileClass::SEVERE); for(auto& d:dc){d.cReqEffSlots=p.cReqEffSlots;d.cResEffSlots=p.cResEffSlots;d.bBlkSlots=p.bBlkSlots;} bBlk=p.bBlkSlots; }
 uint32_t f=ComputeFinish(dc,0,0,bBlk); AdmissionDecision out; out.finishSlots=f; out.slackSlots=static_cast<int64_t>(m_tCtrlSlots)-static_cast<int64_t>(f); out.admit=f<=m_tCtrlSlots; out.reason=out.admit?"admit":"CondB_fail"; return out; }
bool LinkAwareAdmissionController::GroundTruthFeasible(const std::vector<EvCommunicationDemand>& dc) const{ return EvaluateTerminal(dc,AdmissionMode::LINK_AWARE_DEMAND_BASED).admit; }
}
